# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c98b4f142d45fedf716b43020ac4d1155b853c235fb47bbce26cd6dbc66310ec7818e3e924f868811748a6b70626ec82866204d4c054deec41ee1bb19d4044c1

test:
  secret_key_base: 7a92bfc9a5146eaef08abc09eb017ff48976e0fa50fa439ef644b9b9d4c3b833c37a892b6412a104daa78ef6eb04704e64eb2a946af4f61aaf9bcca80042ec76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
